name: AutoRestarter
authors:
  - BaeHyeonWoo
  - theo5970
main: works.baehyeonwoo.autorestarter.AutoMain
version: 0.1
api-version: 1.16
description: "A plugin that automatically restarts server at 12:00 A.M."
website: "https://baehyeonwoo.works/HyeonWeb/SourceCodes/PublicSource"